# == Schema Information
#
# Table name: playlists
# Database name: primary
#
#  id            :integer          not null, primary key
#  description   :text
#  is_public     :boolean          default(FALSE), not null
#  name          :string           not null
#  share_token   :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  grid_hackr_id :integer          not null
#
# Indexes
#
#  index_playlists_on_grid_hackr_id  (grid_hackr_id)
#  index_playlists_on_share_token    (share_token) UNIQUE
#
# Foreign Keys
#
#  grid_hackr_id  (grid_hackr_id => grid_hackrs.id)
#
FactoryBot.define do
  factory :playlist do
    association :grid_hackr
    sequence(:name) { |n| "Playlist #{n}" }
    description { "A test playlist" }
    is_public { false }
    # share_token is auto-generated by the model
  end
end
