FactoryBot.define do
  factory :playlist do
    association :grid_hackr
    sequence(:name) { |n| "Playlist #{n}" }
    description { "A test playlist" }
    is_public { false }
    # share_token is auto-generated by the model
  end
end
