default: &default
  prerelease_mode: null
  prerelease_banner_text: null

development:
  <<: *default
  prerelease_mode: alpha
  prerelease_banner_text: "ALPHA BUILD - Hackr database will be flushed regularly. Please re-register if you cannot log in."

test:
  <<: *default

staging:
  <<: *default
  prerelease_mode: alpha
  prerelease_banner_text: "ALPHA BUILD - Hackr database will be flushed regularly. Please re-register if you cannot log in."

production:
  <<: *default
  prerelease_mode: alpha
  prerelease_banner_text: "ALPHA BUILD - Hackr database will be flushed regularly. Please re-register if you cannot log in."
