# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  code_sync:
    class: CodeSyncJob
    schedule: at 4am every day

  mining_tick:
    class: MiningTickJob
    schedule: every 5 minutes

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  shop_restock:
    class: ShopRestockJob
    schedule: every hour

  shop_rotation:
    class: ShopRotationJob
    schedule: every Monday at midnight
